-- Migration: Add radio_settings table
-- Description: Create radio_settings table with stream configuration and social media URLs
-- Author: Generated by Claude Code
-- Date: 2025-09-19

-- Drop table if exists (for clean migration)
DROP TABLE IF EXISTS `radio_settings`;

-- Create radio_settings table
CREATE TABLE `radio_settings` (
  `id` int NOT NULL AUTO_INCREMENT,
  `stream_url` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  `metadata_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `station_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT 'Trend Ankara Radio',
  `station_description` text COLLATE utf8mb4_unicode_ci,
  `facebook_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `twitter_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `instagram_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `youtube_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_active` (`is_active`),
  KEY `updated_by` (`updated_by`),
  CONSTRAINT `radio_settings_ibfk_1` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default radio settings record
INSERT INTO `radio_settings` (
  `stream_url`,
  `station_name`,
  `station_description`,
  `is_active`,
  `updated_by`
) VALUES (
  'https://stream.example.com/radio',
  'Trend Ankara Radio',
  'Ankara\'s premier radio station bringing you the latest music and entertainment.',
  1,
  NULL
);