-- Migration: Add audit columns to existing tables
-- Description: Add deleted_with_confirmation to news and polls tables, confirmation_required to audit_log table
-- Author: Generated by Claude Code
-- Date: 2025-09-19

-- Add deleted_with_confirmation column to news table
-- This column tracks whether content deletion required confirmation (for requirement 1.6)
ALTER TABLE `news`
ADD COLUMN `deleted_with_confirmation` BOOLEAN NOT NULL DEFAULT FALSE
COMMENT 'Tracks whether content deletion required confirmation step'
AFTER `deleted_at`;

-- Add deleted_with_confirmation column to polls table
-- This column tracks whether content deletion required confirmation (for requirement 1.6)
ALTER TABLE `polls`
ADD COLUMN `deleted_with_confirmation` BOOLEAN NOT NULL DEFAULT FALSE
COMMENT 'Tracks whether content deletion required confirmation step'
AFTER `deleted_at`;

-- Add confirmation_required column to audit_log table
-- This column tracks whether an action required confirmation (for requirement 1.6)
ALTER TABLE `audit_log`
ADD COLUMN `confirmation_required` BOOLEAN NOT NULL DEFAULT FALSE
COMMENT 'Tracks whether the audited action required confirmation step'
AFTER `session_id`;

-- Add indexes for the new audit columns to support efficient querying
ALTER TABLE `news` ADD INDEX `idx_news_deleted_confirmation` (`deleted_with_confirmation`);
ALTER TABLE `polls` ADD INDEX `idx_polls_deleted_confirmation` (`deleted_with_confirmation`);
ALTER TABLE `audit_log` ADD INDEX `idx_audit_log_confirmation` (`confirmation_required`);