-- Migration: Seed radio_settings table with initial configuration
-- Description: Insert default radio configuration data from environment
-- Author: Generated by Claude Code
-- Date: 2025-09-19

-- Clear any existing data (for clean seeding)
DELETE FROM `radio_settings`;

-- Insert initial radio settings with production configuration
INSERT INTO `radio_settings` (
  `stream_url`,
  `metadata_url`,
  `station_name`,
  `station_description`,
  `facebook_url`,
  `twitter_url`,
  `instagram_url`,
  `youtube_url`,
  `is_active`,
  `created_at`,
  `updated_at`,
  `updated_by`
) VALUES (
  'https://radyo.yayin.com.tr:5132/stream',
  'https://radyo.yayin.com.tr:5132/',
  'Trend Ankara Radio',
  'Professional Turkish Radio Station delivering quality music and entertainment to Ankara and beyond.',
  NULL,
  NULL,
  NULL,
  NULL,
  1,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP,
  NULL
);

-- Reset AUTO_INCREMENT to ensure consistent IDs
ALTER TABLE `radio_settings` AUTO_INCREMENT = 2;