name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          password: ${{ secrets.VPS_PASSWORD }} # Add your root password as secret
          script: |
            cd /opt/app
            git pull
            docker build -t radioapp .
            docker stop radioapp || true
            docker rm radioapp || true

            # Ensure the network exists
            docker network create radio_network_alt 2>/dev/null || true

            # Ensure MySQL and MinIO are connected to the network
            docker network connect radio_network_alt radio_mysql_alt 2>/dev/null || true
            docker network connect radio_network_alt minio 2>/dev/null || true

            # Run the container with all required environment variables
            docker run -d \
              --name radioapp \
              --network radio_network_alt \
              -p 3000:3000 \
              --restart always \
              -e NODE_ENV=production \
              -e DATABASE_HOST=radio_mysql_alt \
              -e DATABASE_PORT=3306 \
              -e DATABASE_USER=root \
              -e DATABASE_PASSWORD=radiopass123 \
              -e DATABASE_NAME=radio_db \
              -e NEXTAUTH_URL=https://www.trendankara.com \
              -e NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" \
              -e AUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" \
              -e MINIO_ENDPOINT=minio \
              -e MINIO_PORT=9000 \
              -e MINIO_ACCESS_KEY=minioadmin \
              -e MINIO_SECRET_KEY=minioadmin123 \
              -e MINIO_BUCKET=media \
              -e MINIO_USE_SSL=false \
              -e RADIO_STREAM_URL=https://radyo.yayin.com.tr:5132/stream \
              -e RADIO_METADATA_URL=https://radyo.yayin.com.tr:5132/ \
              radioapp
