name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          password: ${{ secrets.VPS_PASSWORD }} # Add your root password as secret
          script: |
            cd /opt/app
            git pull
            docker build -t radioapp .
            docker stop radioapp || true
            docker rm radioapp || true

            # Ensure the network exists
            docker network create radio_network_alt 2>/dev/null || true

            # Ensure MySQL and MinIO are connected to the network
            docker network connect radio_network_alt radio_mysql_alt 2>/dev/null || true
            docker network connect radio_network_alt minio 2>/dev/null || true

            # Run the container with all required environment variables
            docker run -d \
              --name radioapp \
              --network radio_network_alt \
              -p 3000:3000 \
              --restart always \
              -e NODE_ENV=production \
              -e DATABASE_HOST=radio_mysql_alt \
              -e DATABASE_PORT=3306 \
              -e DATABASE_USER=root \
              -e DATABASE_PASSWORD=radiopass123 \
              -e DATABASE_NAME=radio_db \
              -e NEXTAUTH_URL=https://www.trendankara.com \
              -e NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" \
              -e AUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" \
              -e MINIO_ENDPOINT=minio \
              -e MINIO_PORT=9000 \
              -e MINIO_ACCESS_KEY=minioadmin \
              -e MINIO_SECRET_KEY=minioadmin123 \
              -e MINIO_BUCKET=media \
              -e MINIO_USE_SSL=false \
              -e RADIO_STREAM_URL=https://radyo.yayin.com.tr:5132/stream \
              -e RADIO_METADATA_URL=https://radyo.yayin.com.tr:5132/ \
              -e RADIO_BACKUP_STREAM_URL=https://radyo.yayin.com.tr:5132/stream \
              -e RADIO_CORS_PROXY=https://cros9.yayin.com.tr \
              -e STREAM_TEST_RATE_LIMIT=10 \
              -e GENERAL_API_RATE_LIMIT=100 \
              -e RADIO_CONFIG_CACHE_TIMEOUT=30 \
              -e CONTENT_CACHE_TIMEOUT=300 \
              -e FEATURE_CONFIRM_DELETIONS=true \
              -e FEATURE_RADIO_SETTINGS=true \
              -e FEATURE_REALTIME_UPDATES=true \
              -e FEATURE_RATE_LIMITING=true \
              -e DEFAULT_ADMIN_ROLE=admin \
              -e REQUIRE_SUPER_ADMIN_FOR_STREAMS=false \
              -e DATABASE_CONNECTION_LIMIT=10 \
              -e DATABASE_TIMEOUT=10000 \
              -e LOG_LEVEL=info \
              -e ENABLE_API_LOGGING=false \
              -e API_VERSION=v1 \
              -e MOBILE_API_KEY="${{ secrets.MOBILE_API_KEY }}" \
              -e RATE_LIMIT_MOBILE=100 \
              -e SITE_NAME="Trend Ankara Radio" \
              -e SITE_URL=https://www.trendankara.com \
              -e SITE_DESCRIPTION="Professional Turkish Radio Station" \
              radioapp
