name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          password: ${{ secrets.VPS_PASSWORD }} # Add your root password as secret
          script: |
            cd /opt/app
            git pull
            docker build -t radioapp .
            docker stop radioapp || true
            docker rm radioapp || true
            docker run -d --name radioapp --network radio-network -p 3000:3000 --restart always radioapp
